### PR TITLE
Support SkiaFiddle in Visual Studio 8.5

### PR DESCRIPTION
**Pull request by matthewrdev**

### CODE REVIEW

**Comment by matthewrdev** [comment]
Fixes #3

**Comment by matthewrdev** [comment]
@jsuarezruiz  This PR should be ready to go if you'd like to review it :)

**Comment by LuckyDucko** [comment]
@jsuarezruiz I have tested @matthewrdev changes and was able to build/deploy on the latest VS4mac, and used it to build some SkiaSharp designs without any hassle.

This is a basic example I took today showing

basic example

This is the example add-on I built from Matthews repo, Incase anyone wanted to try themselves as this is a very useful add-on
[MonoDevelop.SkiaSharpFiddle_0.2.mpack.zip](https://github.com/jsuarezruiz/VS4Mac-SkiaSharpFiddle/files/5107208/MonoDevelop.SkiaSharpFiddle_0.2.mpack.zip)

**Comment by jsuarezruiz** [comment]
Thanks so much @matthewrdev!

**Comment by matthewrdev** [comment]
@jsuarezruiz My pleasure!

**Pull request merged**
